events {}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;

        # Serve o Frontend Estático
        location / {
            root   /usr/share/nginx/html;
            index  index.html;
            try_files $uri $uri/ /index.html;
        }

        # Proxy reverso para a API
        location /api/ {
            proxy_pass         http://api:8000;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
        }
    }
}